### ISSUE TITLE
如何将oas文件转成网络的输入的文件啊

### ISSUE THREAD

**Issue by myalos** [Lanselott/R-HSD#1]
大佬你好，感谢分享代码！最近刚开始接触hotspot detection，我下载了ICCAD2012的gds文件，打开看后发现是许多个2.8um的正方形的pattern，请问这个如何转化成深度学习常用的224x224的网络输入啊

**Comment by tttStudy** [comment]
您好，R-HSD源码用于训练和测试的数据集文件可以共享吗？

**Comment by Lanselott** [comment]
try this: https://gdspy.readthedocs.io/en/stable/gettingstarted.html

**Comment by faguo** [comment]
请问一下iccad2012的数据集链接可以提供一下吗，找到的链接都失效了
